name: servicio-front

namespace: otsugua04-dev

container:
  tag: "build-{{ tag }}"
  port: 8080
  image: "otsugua04/servicio-front"
  replicas: 2
  cpuRequests: "500m"
  memRequests: "800Mi"
  cpuLimits: "1000m"
  memLimits: "1500Mi"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configmap:
  servicio_backend_url: "http://servicio-backend-service.otsugua04-dev.svc.cluster.local/api/info/"
